// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0GJZrcvXg--mEqTFv0neAUWXyktfnYH8',
    appId: '1:765697907823:web:a086d735805036f66d019a',
    messagingSenderId: '765697907823',
    projectId: 'attendify-8f698',
    authDomain: 'attendify-8f698.firebaseapp.com',
    storageBucket: 'attendify-8f698.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2-24B10FMCZjwLhslIZpYcBYlguO25ug',
    appId: '1:765697907823:android:15e04607795e13a96d019a',
    messagingSenderId: '765697907823',
    projectId: 'attendify-8f698',
    storageBucket: 'attendify-8f698.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgOSKdg4N8p4zOFXLTc9T4AhKe2pR4rrg',
    appId: '1:765697907823:ios:26c83ca094e457b26d019a',
    messagingSenderId: '765697907823',
    projectId: 'attendify-8f698',
    storageBucket: 'attendify-8f698.appspot.com',
    iosClientId: '765697907823-1risasl7gvg17koae6t629jmr4ctntvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendancetrackerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgOSKdg4N8p4zOFXLTc9T4AhKe2pR4rrg',
    appId: '1:765697907823:ios:26c83ca094e457b26d019a',
    messagingSenderId: '765697907823',
    projectId: 'attendify-8f698',
    storageBucket: 'attendify-8f698.appspot.com',
    iosClientId: '765697907823-1risasl7gvg17koae6t629jmr4ctntvo.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendancetrackerFlutter',
  );
}
